### ISSUE TITLE
Project Overview

### ISSUE THREAD

**Issue by hmontero1205** [oliveo90/bwa-u3-jammming-prj#3]
Overall, your work meets the project specifications -- great job!!

I actually do not have any issues with your code. Everything works like it's supposed to and you passed the edge cases I tried throwing at the site. Maybe comment your code more from now on? A few words before a complicated function goes a long way in terms of documentation.

Best of luck and keep it up :)

**Comment by oliveo90** [comment]
Thanks Hans! I'm glad the app works. I learnt a great deal while creating it.
