### ISSUE TITLE
Feature Request Review

### ISSUE THREAD

**Issue by mp1pro** [oliveo90/bwa-u3-jammming-prj#4]
Adding the ability to trigger the search function by pressing enter button will indeed make the app faster to navigate. The description given in the technical design is correct. However, some example codes should be given like so;
```
  handleEnter(event) {
    if(event.keyCode === 13) {
      this.search();
    }
}
```
and
`<input onKeyDown={this.handleEnter}/>`

**Comment by oliveo90** [comment]
Great to know. I didn't realize I could include codes in the document. Thanks
